// level 4
const Fall = require('./assets/level-4/fall.png');
const Spring = require('./assets/level-4/spring.png');
const Summer = require('./assets/level-4/summer.png');
const Winter = require('./assets/level-4/winter.png');
// level 5
const Bag = require('./assets/level-5/bag.png');
const Eraser = require('./assets/level-5/eraser.png');
const Pen = require('./assets/level-5/pen.png');
const Pencil = require('./assets/level-5/pencil.png');
const Ruler = require('./assets/level-5/ruler.png');
// level 6
const Bird = require('./assets/level-6/bird.png');
const Cat = require('./assets/level-6/cat.png');
const Dog = require('./assets/level-6/dog.png');
const Fish = require('./assets/level-6/fish.png');
const Rabbit = require('./assets/level-6/rabbit.png');
// level 7
const ColorBlack = require('./assets/level-7/black.png');
const ColorGrey = require('./assets/level-7/grey.png');
const ColorBrown = require('./assets/level-7/brown.png');
const ColorPurple = require('./assets/level-7/purple.png');
const ColorWhite = require('./assets/level-7/white.png');

import {
  FILL_THE_BLANK,
  MULTIPLE_CHOICE,
  MULTIPLE_CHOICE_IMAGES,
  PAIR_SELECTION,
  PRONOUNCE_THE_WORD,
  SPELLING_ORDER,
} from '../../../environments/Routes';

export const STAGE_TWO = [
  //fourth level
  [
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What season is it ?',
        possibleAnswersCount: 4,
        answers: ['spring', 'summer', 'fall', 'winter'],
        correctAnswer: 'winter',
        imageAsset: Winter,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose SPRING',
        answers: [
          {
            name: 'winter',
            asset: Winter,
          },
          {
            name: 'fall',
            asset: Fall,
          },
          {
            name: 'spring',
            asset: Spring,
          },
          {
            name: 'summer',
            asset: Summer,
          },
        ],
        correctAnswer: 'spring',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-1',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['winter', 'spring'],
        imagesAsset: [
          {
            name: 'winter',
            asset: Winter,
          },
          {
            name: 'spring',
            asset: Spring,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What season is it ?',
        possibleAnswersCount: 4,
        answers: ['spring', 'summer', 'winter', 'fall'],
        correctAnswer: 'fall',
        imageAsset: Fall,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '08-04-2020',
        updatedAt: '08-04-2020',
        type: FILL_THE_BLANK,
        questionContent: 'It is',
        possibleAnswersCount: 4,
        answers: ['winter', 'fall', 'summer', 'spring'],
        correctAnswer: 'fall',
        imageAsset: Fall,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['spring', 'winter', 'fall'],
        imagesAsset: [
          {
            name: 'spring',
            asset: Spring,
          },
          {
            name: 'winter',
            asset: Winter,
          },
          {
            name: 'fall',
            asset: Fall,
          },
        ],
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the word',
        imageAsset: Fall,
        correctAnswer: 'fall',
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose SUMMER',
        answers: [
          {
            name: 'winter',
            asset: Winter,
          },
          {
            name: 'fall',
            asset: Fall,
          },
          {
            name: 'summer',
            asset: Summer,
          },
          {
            name: 'spring',
            asset: Spring,
          },
        ],
        correctAnswer: 'summer',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell the word',
        possibleAnswersCount: 4,
        answers: ['m', 'm', 'u', 'e', 'r', 's'],
        correctAnswer: 'summer',
        imageAsset: Summer,
        correctAnswerCount: 1,
      },
      {
        id: 'q5',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['spring', 'summer', 'winter'],
        imagesAsset: [
          {
            name: 'spring',
            asset: Spring,
          },
          {
            name: 'summer',
            asset: Summer,
          },
          {
            name: 'winter',
            asset: Winter,
          },
        ],
        correctAnswerCount: 1,
      },
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What season is it ?',
        possibleAnswersCount: 4,
        answers: ['fall', 'summer', 'winter', 'spring'],
        correctAnswer: 'summer',
        imageAsset: Summer,
        correctAnswerCount: 1,
      },
      {
        id: 'q5',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['spring', 'summer', 'fall', 'winter'],
        imagesAsset: [
          {
            name: 'spring',
            asset: Spring,
          },
          {
            name: 'summer',
            asset: Summer,
          },
          {
            name: 'fall',
            asset: Fall,
          },
          {
            name: 'winter',
            asset: Winter,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
  ],

  //fifth level
  [
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What is it ?',
        possibleAnswersCount: 4,
        answers: ['bag', 'pen', 'pencil', 'eraser'],
        correctAnswer: 'pencil',
        imageAsset: Pencil,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose ERASER',
        answers: [
          {
            name: 'eraser',
            asset: Eraser,
          },
          {
            name: 'pen',
            asset: Pen,
          },
          {
            name: 'bag',
            asset: Bag,
          },
          {
            name: 'pencil',
            asset: Pencil,
          },
        ],
        correctAnswer: 'eraser',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-1',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['pencil', 'eraser'],
        imagesAsset: [
          {
            name: 'pencil',
            asset: Pencil,
          },
          {
            name: 'eraser',
            asset: Eraser,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose PEN',
        answers: [
          {
            name: 'eraser',
            asset: Eraser,
          },
          {
            name: 'pen',
            asset: Pen,
          },
          {
            name: 'pencil',
            asset: Pencil,
          },
          {
            name: 'bag',
            asset: Bag,
          },
        ],
        correctAnswer: 'pen',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What is it ?',
        possibleAnswersCount: 4,
        answers: ['pencil', 'eraser', 'pen', 'bag'],
        correctAnswer: 'bag',
        imageAsset: Bag,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell the word',
        possibleAnswersCount: 4,
        answers: ['n', 'p', 'e', 'c', 'l', 'i'],
        correctAnswer: 'pencil',
        imageAsset: Pencil,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['eraser', 'pen', 'bag', 'pencil'],
        imagesAsset: [
          {
            name: 'eraser',
            asset: Eraser,
          },
          {
            name: 'pen',
            asset: Pen,
          },
          {
            name: 'bag',
            asset: Bag,
          },
          {
            name: 'pencil',
            asset: Pencil,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What is it ?',
        possibleAnswersCount: 4,
        answers: ['ruler', 'pencil', 'eraser', 'bag'],
        correctAnswer: 'ruler',
        imageAsset: Ruler,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell the word',
        possibleAnswersCount: 4,
        answers: ['u', 'r', 'l', 'e', 'r'],
        correctAnswer: 'ruler',
        imageAsset: Ruler,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '08-04-2020',
        updatedAt: '08-04-2020',
        type: FILL_THE_BLANK,
        questionContent: 'It is a',
        possibleAnswersCount: 4,
        answers: ['ruler', 'bag', 'pen', 'pencil'],
        correctAnswer: 'ruler',
        imageAsset: Ruler,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the word',
        imageAsset: Pen,
        correctAnswer: 'pen',
        correctAnswerCount: 1,
      },
      {
        id: 'q5',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['pen', 'bag', 'ruler', 'eraser'],
        imagesAsset: [
          {
            name: 'pen',
            asset: Pen,
          },
          {
            name: 'bag',
            asset: Bag,
          },
          {
            name: 'ruler',
            asset: Ruler,
          },
          {
            name: 'eraser',
            asset: Eraser,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
  ],

  //sixth level
  [
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-3',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose DOG',
        answers: [
          {
            name: 'dog',
            asset: Dog,
          },
          {
            name: 'cat',
            asset: Cat,
          },
          {
            name: 'bird',
            asset: Bird,
          },
          {
            name: 'fish',
            asset: Fish,
          },
        ],
        correctAnswer: 'dog',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-3',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What animal is it ?',
        possibleAnswersCount: 4,
        answers: ['dog', 'cat', 'bird', 'fish'],
        correctAnswer: 'cat',
        imageAsset: Cat,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-1',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['dog', 'cat'],
        imagesAsset: [
          {
            name: 'dog',
            asset: Dog,
          },
          {
            name: 'cat',
            asset: Cat,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What animal is it ?',
        possibleAnswersCount: 4,
        answers: ['dog', 'cat', 'bird', 'fish'],
        correctAnswer: 'bird',
        imageAsset: Bird,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the word',
        imageAsset: Cat,
        correctAnswer: 'cat',
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose FISH',
        answers: [
          {
            name: 'dog',
            asset: Dog,
          },
          {
            name: 'cat',
            asset: Cat,
          },
          {
            name: 'bird',
            asset: Bird,
          },
          {
            name: 'fish',
            asset: Fish,
          },
        ],
        correctAnswer: 'fish',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['bird', 'cat', 'fish', 'dog'],
        imagesAsset: [
          {
            name: 'bird',
            asset: Bird,
          },
          {
            name: 'cat',
            asset: Cat,
          },
          {
            name: 'fish',
            asset: Fish,
          },
          {
            name: 'dog',
            asset: Dog,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose RABBIT',
        answers: [
          {
            name: 'dog',
            asset: Dog,
          },
          {
            name: 'cat',
            asset: Cat,
          },
          {
            name: 'rabbit',
            asset: Rabbit,
          },
          {
            name: 'fish',
            asset: Fish,
          },
        ],
        correctAnswer: 'rabbit',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '08-04-2020',
        updatedAt: '08-04-2020',
        type: FILL_THE_BLANK,
        questionContent: 'It is a ',
        possibleAnswersCount: 4,
        answers: ['cat', 'pig', 'dog', 'fish'],
        correctAnswer: 'fish',
        imageAsset: Fish,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the word',
        imageAsset: Rabbit,
        correctAnswer: 'rabbit',
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell the word',
        possibleAnswersCount: 4,
        answers: ['r', 'd', 'i', 'b'],
        correctAnswer: 'bird',
        imageAsset: Bird,
        correctAnswerCount: 1,
      },
      {
        id: 'q5',
        stage: 'stage-2',
        level: 'level-2',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['rabbit', 'fish', 'bird', 'dog'],
        imagesAsset: [
          {
            name: 'rabbit',
            asset: Rabbit,
          },
          {
            name: 'fish',
            asset: Fish,
          },
          {
            name: 'bird',
            asset: Bird,
          },
          {
            name: 'dog',
            asset: Dog,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
  ],

  // seventh Level
  [
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What color is it ?',
        possibleAnswersCount: 4,
        answers: ['purple', 'brown', 'black', 'white'],
        correctAnswer: 'purple',
        imageAsset: ColorPurple,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose BROWN',
        answers: [
          {
            name: 'purple',
            asset: ColorPurple,
          },
          {
            name: 'brown',
            asset: ColorBrown,
          },
          {
            name: 'black',
            asset: ColorBlack,
          },
          {
            name: 'white',
            asset: ColorWhite,
          },
        ],
        correctAnswer: 'brown',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-1',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['purple', 'brown'],
        imagesAsset: [
          {
            name: 'purple',
            asset: ColorPurple,
          },
          {
            name: 'brown',
            asset: ColorBrown,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What color is it ?',
        possibleAnswersCount: 4,
        answers: ['purple', 'brown', 'black', 'white'],
        correctAnswer: 'black',
        imageAsset: ColorBlack,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '08-04-2020',
        updatedAt: '08-04-2020',
        type: FILL_THE_BLANK,
        questionContent: 'The color is',
        possibleAnswersCount: 4,
        answers: ['brown', 'black', 'purple', 'blue'],
        correctAnswer: 'brown',
        imageAsset: ColorBrown,
        correctAnswerCount: 1,
      },
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose WHITE',
        answers: [
          {
            name: 'purple',
            asset: ColorPurple,
          },
          {
            name: 'brown',
            asset: ColorBrown,
          },
          {
            name: 'black',
            asset: ColorBlack,
          },
          {
            name: 'white',
            asset: ColorWhite,
          },
        ],
        correctAnswer: 'white',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['purple', 'brown', 'black', 'white'],
        imagesAsset: [
          {
            name: 'purple',
            asset: ColorPurple,
          },
          {
            name: 'brown',
            asset: ColorBrown,
          },
          {
            name: 'black',
            asset: ColorBlack,
          },
          {
            name: 'white',
            asset: ColorWhite,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose GREY',
        answers: [
          {
            name: 'purple',
            asset: ColorPurple,
          },
          {
            name: 'brown',
            asset: ColorBrown,
          },
          {
            name: 'grey',
            asset: ColorGrey,
          },
          {
            name: 'white',
            asset: ColorWhite,
          },
        ],
        correctAnswer: 'grey',
        imageAsset: null,
        correctAnswerCount: 1,
      },

      {
        id: 'q2',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '08-04-2020',
        updatedAt: '08-04-2020',
        type: FILL_THE_BLANK,
        questionContent: 'The color is',
        possibleAnswersCount: 4,
        answers: ['white', 'orange', 'black', 'brown'],
        correctAnswer: 'white',
        imageAsset: ColorWhite,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the word',
        imageAsset: ColorGrey,
        correctAnswer: 'grey',
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell the word',
        possibleAnswersCount: 4,
        answers: ['r', 'e', 'y', 'g'],
        correctAnswer: 'grey',
        imageAsset: ColorGrey,
        correctAnswerCount: 1,
      },

      {
        id: 'q5',
        stage: 'stage-2',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Choose the pairs',
        answers: ['grey', 'white', 'purple', 'black'],
        imagesAsset: [
          {
            name: 'grey',
            asset: ColorGrey,
          },
          {
            name: 'white',
            asset: ColorWhite,
          },
          {
            name: 'purple',
            asset: ColorPurple,
          },
          {
            name: 'black',
            asset: ColorBlack,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
  ],
];
