//progress reducer
export const PLAY = 'PLAY';
export const REPLAY = 'REPLAY';
export const STOP = 'STOP';
export const COMPLETED_A_QUESTION = 'COMPLETED_A_QUESTION';
export const COMPLETED_A_REPLAY_QUESTION = 'COMPLETED_A_REPLAY_QUESTION';
export const COMPLETED_A_TEST = 'COMPLETED_A_TEST';
export const COMPLETED_A_LEVEL = 'COMPLETED_A_LEVEL';
export const COMPLETED_A_STAGE = 'COMPLETED_A_STAGE';

//questions content reducer
export const INITIALIZE_QUESTIONS = 'INITIALIZE_QUESTIONS';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';

//vocabularies reducer
export const ADD_NEW_VOCABULARY = 'ADD_NEW_VOCABULARY';
export const REMOVE_VOCABULARY = 'REMOVE_VOCABULARY';

//progress counter reducer
export const INCREMENT_QUESTION_COUNTER = 'INCREMENT_QUESTION_COUNTER';
export const INCREMENT_TEST_COUNTER = 'INCREMENT_TEST_COUNTER';
export const INCREMENT_LEVEL_COUNTER = 'INCREMENT_LEVEL_COUNTER';
export const INCREMENT_STAGE_COUNTER = 'INCREMENT_STAGE_COUNTER';

//user reducer
export const SIGNING_IN = 'SIGNING_IN';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGNED_IN = 'SIGNED_IN';
