// level 1
const ColorRed = require('./assets/level-1/red-color.png');
const ColorYellow = require('./assets/level-1/yellow-color.png');
const ColorGreen = require('./assets/level-1/green-color.png');
const ColorBlue = require('./assets/level-1/blue-color.png');
const ColorOrange = require('./assets/level-1/orange-color.png');
// level 2
const Arm = require('./assets/level-2/arm.png');
const Ear = require('./assets/level-2/ear.png');
const Hand = require('./assets/level-2/hand.png');
const Head = require('./assets/level-2/head.png');
const Leg = require('./assets/level-2/leg.png');
// level 3
const Apple = require('./assets/level-3/apple.png');
const Banana = require('./assets/level-3/banana.png');
const Orange = require('./assets/level-3/orange.png');
const Mango = require('./assets/level-3/mango.png');
const Strawberry = require('./assets/level-3/strawberry.png');
import {
  FILL_THE_BLANK,
  FIND_THE_OBJECT,
  MULTIPLE_CHOICE,
  MULTIPLE_CHOICE_IMAGES,
  PAIR_SELECTION,
  PRONOUNCE_THE_WORD,
  SPELLING_ORDER,
} from '../../../environments/Routes';

export const STAGE_ONE = [
  //first level
  [
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What color is this ?',
        possibleAnswersCount: 4,
        answers: ['red', 'yellow', 'green', 'orange'],
        correctAnswer: 'red',
        imageAsset: ColorRed,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose YELLOW',
        answers: [
          {
            name: 'red',
            asset: ColorRed,
          },
          {
            name: 'green',
            asset: ColorGreen,
          },
          {
            name: 'yellow',
            asset: ColorYellow,
          },
          {
            name: 'orange',
            asset: ColorOrange,
          },
        ],
        correctAnswer: 'yellow',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-1',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['yellow', 'red'],
        imagesAsset: [
          {
            name: 'yellow',
            asset: ColorYellow,
          },
          {
            name: 'red',
            asset: ColorRed,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What color is this ?',
        possibleAnswersCount: 4,
        answers: ['red', 'yellow', 'green', 'orange'],
        correctAnswer: 'green',
        imageAsset: ColorGreen,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: FILL_THE_BLANK,
        questionContent: 'The color of the Banana is',
        possibleAnswersCount: 4,
        answers: ['yellow', 'green', 'red', 'white'],
        correctAnswer: 'yellow',
        imageAsset: Banana,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose ORANGE',
        answers: [
          {
            name: 'red',
            asset: ColorRed,
          },
          {
            name: 'green',
            asset: ColorGreen,
          },
          {
            name: 'yellow',
            asset: ColorYellow,
          },
          {
            name: 'orange',
            asset: ColorOrange,
          },
        ],
        correctAnswer: 'orange',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['yellow', 'red', 'green', 'orange'],
        imagesAsset: [
          {
            name: 'yellow',
            asset: ColorYellow,
          },
          {
            name: 'red',
            asset: ColorRed,
          },
          {
            name: 'green',
            asset: ColorGreen,
          },
          {
            name: 'orange',
            asset: ColorOrange,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose BLUE',
        answers: [
          {
            name: 'red',
            asset: ColorRed,
          },
          {
            name: 'green',
            asset: ColorGreen,
          },
          {
            name: 'blue',
            asset: ColorBlue,
          },
          {
            name: 'orange',
            asset: ColorOrange,
          },
        ],
        correctAnswer: 'blue',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-3',
        createdAt: '08-04-2020',
        updatedAt: '08-04-2020',
        type: FILL_THE_BLANK,
        questionContent: 'The color of the Orange is',
        possibleAnswersCount: 4,
        answers: ['white', 'orange', 'green', 'yellow'],
        correctAnswer: 'orange',
        imageAsset: Orange,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the color blue',
        imageAsset: ColorBlue,
        correctAnswer: 'blue',
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell the word',
        possibleAnswersCount: 4,
        answers: ['e', 'u', 'b', 'l'],
        correctAnswer: 'blue',
        imageAsset: ColorBlue,
        correctAnswerCount: 1,
      },
      {
        id: 'q5',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['orange', 'red', 'green', 'blue'],
        imagesAsset: [
          {
            name: 'orange',
            asset: ColorOrange,
          },
          {
            name: 'red',
            asset: ColorRed,
          },
          {
            name: 'green',
            asset: ColorGreen,
          },
          {
            name: 'blue',
            asset: ColorBlue,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
  ],

  //second level
  [
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What body part is this ?',
        possibleAnswersCount: 4,
        answers: ['head', 'hand', 'leg', 'back'],
        correctAnswer: 'head',
        imageAsset: Head,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose ARM',
        answers: [
          {
            name: 'arm',
            asset: Arm,
          },
          {
            name: 'leg',
            asset: Leg,
          },
          {
            name: 'head',
            asset: Head,
          },
          {
            name: 'ear',
            asset: Ear,
          },
        ],
        correctAnswer: 'arm',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-1',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['head', 'arm'],
        imagesAsset: [
          {
            name: 'head',
            asset: Head,
          },
          {
            name: 'arm',
            asset: Arm,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose LEG',
        answers: [
          {
            name: 'leg',
            asset: Leg,
          },
          {
            name: 'arm',
            asset: Arm,
          },
          {
            name: 'head',
            asset: Head,
          },
          {
            name: 'ear',
            asset: Ear,
          },
        ],
        correctAnswer: 'leg',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What body part is this ?',
        possibleAnswersCount: 4,
        answers: ['hand', 'foot', 'leg', 'head'],
        correctAnswer: 'hand',
        imageAsset: Hand,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell this word',
        possibleAnswersCount: 4,
        answers: ['m', 'r', 'a'],
        correctAnswer: 'arm',
        imageAsset: Arm,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['head', 'hand', 'leg'],
        imagesAsset: [
          {
            name: 'head',
            asset: Head,
          },
          {
            name: 'hand',
            asset: Hand,
          },
          {
            name: 'leg',
            asset: Leg,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What body part is this ?',
        possibleAnswersCount: 4,
        answers: ['hand', 'head', 'leg', 'ear'],
        correctAnswer: 'ear',
        imageAsset: Ear,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-3',
        createdAt: '14-05-2020',
        updatedAt: '14-05-2020',
        type: FIND_THE_OBJECT,
        questionContent: 'Take a photo of an EAR',
        correctAnswer: 'ear',
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['head', 'hand', 'ear'],
        imagesAsset: [
          {
            name: 'head',
            asset: Head,
          },
          {
            name: 'hand',
            asset: Hand,
          },
          {
            name: 'ear',
            asset: Ear,
          },
        ],
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-3',
        createdAt: '14-05-2020',
        updatedAt: '14-05-2020',
        type: FIND_THE_OBJECT,
        questionContent: 'Take a photo of a LEG',
        correctAnswer: 'leg',
        correctAnswerCount: 1,
      },
      {
        id: 'q5',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['arm', 'leg', 'hand', 'ear'],
        imagesAsset: [
          {
            name: 'arm',
            asset: Arm,
          },
          {
            name: 'leg',
            asset: Leg,
          },
          {
            name: 'hand',
            asset: Hand,
          },
          {
            name: 'ear',
            asset: Ear,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
  ],

  //third level
  [
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-3',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose APPLE',
        answers: [
          {
            name: 'apple',
            asset: Apple,
          },
          {
            name: 'banana',
            asset: Banana,
          },
          {
            name: 'orange',
            asset: Orange,
          },
          {
            name: 'strawberry',
            asset: Strawberry,
          },
        ],
        correctAnswer: 'apple',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-3',
        test: 'test-1',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'What fruit is this ?',
        possibleAnswersCount: 4,
        answers: ['banana', 'apple', 'strawberry', 'orange'],
        correctAnswer: 'banana',
        imageAsset: Banana,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-1',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['apple', 'banana'],
        imagesAsset: [
          {
            name: 'apple',
            asset: Apple,
          },
          {
            name: 'banana',
            asset: Banana,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE,
        questionContent: 'Which fruit is this ?',
        possibleAnswersCount: 4,
        answers: ['apple', 'strawberry', 'banana', 'orange'],
        correctAnswer: 'orange',
        imageAsset: Orange,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the word',
        imageAsset: Banana,
        correctAnswer: 'banana',
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose STRAWBERRY',
        answers: [
          {
            name: 'strawberry',
            asset: Strawberry,
          },
          {
            name: 'apple',
            asset: Apple,
          },
          {
            name: 'orange',
            asset: Orange,
          },
          {
            name: 'banana',
            asset: Banana,
          },
        ],
        correctAnswer: 'strawberry',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['orange', 'banana', 'strawberry', 'apple'],
        imagesAsset: [
          {
            name: 'orange',
            asset: Orange,
          },
          {
            name: 'banana',
            asset: Banana,
          },
          {
            name: 'strawberry',
            asset: Strawberry,
          },
          {
            name: 'apple',
            asset: Apple,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
    [
      {
        id: 'q1',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-3',
        createdAt: '02-05-2020',
        updatedAt: '02-05-2020',
        type: MULTIPLE_CHOICE_IMAGES,
        questionContent: 'Choose MANGO',
        answers: [
          {
            name: 'apple',
            asset: Apple,
          },
          {
            name: 'mango',
            asset: Mango,
          },
          {
            name: 'orange',
            asset: Orange,
          },
          {
            name: 'banana',
            asset: Banana,
          },
        ],
        correctAnswer: 'mango',
        imageAsset: null,
        correctAnswerCount: 1,
      },
      {
        id: 'q2',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-3',
        createdAt: '08-04-2020',
        updatedAt: '08-04-2020',
        type: FILL_THE_BLANK,
        questionContent: 'This is a ',
        possibleAnswersCount: 4,
        answers: ['strawberry', 'mango', 'apple', 'orange'],
        correctAnswer: 'strawberry',
        imageAsset: Strawberry,
        correctAnswerCount: 1,
      },
      {
        id: 'q3',
        stage: 'stage-1',
        level: 'level-1',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PRONOUNCE_THE_WORD,
        questionContent: 'Say the word',
        imageAsset: Mango,
        correctAnswer: 'mango',
        correctAnswerCount: 1,
      },
      {
        id: 'q4',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-2',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: SPELLING_ORDER,
        questionContent: 'Spell the word',
        possibleAnswersCount: 4,
        answers: ['e', 'n', 'r', 'o', 'a', 'g'],
        correctAnswer: 'orange',
        imageAsset: Orange,
        correctAnswerCount: 1,
      },
      {
        id: 'q5',
        stage: 'stage-1',
        level: 'level-2',
        test: 'test-3',
        createdAt: '14-04-2020',
        updatedAt: '14-04-2020',
        type: PAIR_SELECTION,
        questionContent: 'Match the pairs',
        answers: ['mango', 'strawberry', 'orange', 'apple'],
        imagesAsset: [
          {
            name: 'mango',
            asset: Mango,
          },
          {
            name: 'strawberry',
            asset: Strawberry,
          },
          {
            name: 'orange',
            asset: Orange,
          },
          {
            name: 'apple',
            asset: Apple,
          },
        ],
        correctAnswerCount: 1,
      },
    ],
  ],
];
